### ISSUE TITLE
KeyError: 'session_info' run error

### ISSUE THREAD

**Issue by ghachey** [pppontusw/dl-nhltv#22]
Getting error below.

```
Jan 23 02:56:29 - Logging in to NHL.com..
Jan 23 02:56:30 - Looking up games..
Traceback (most recent call last):
  File "/usr/local/bin/nhltv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 39, in main
    run_loop()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 44, in run_loop
    loop()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 48, in loop
    get_and_download_games()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 71, in get_and_download_games
    download(i)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 79, in download
    dl: Download = download_game(stream)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/download.py", line 40, in download_game
    download = _get_download_from_stream(stream)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/download.py", line 104, in _get_download_from_stream
    media_auth: str = _extract_media_auth(stream_json)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/download.py", line 187, in _extract_media_auth
    session_json["session_info"]["sessionAttributes"][0][
KeyError: 'session_info'
```

**Comment by pppontusw** [comment]
Hey there, any chance you could share with me what parameters you ran the program with (except for username and password of course) - especially what team and if you passed in any special interval (with the -i option) - so I can see if I can reproduce this with the same game perhaps

**Comment by pppontusw** [comment]
I published a new version (2.1.2) which should log the API response messages when the "session_info" key is missing, can you try with that one? 

I suspect that the API somehow doesn't think you're authorized to view the game, but I'm not sure how that can be the case (since you mentioned authentication works). If you run the latest version, please copy the error message here and let's see if it helps explain what's happening

**Comment by pppontusw** [comment]
During looking into this, I noticed that NHLTV sells a single team package, is it possible that you have that package? I know I haven't tested the app with that kind of subscription, so that's one possibility that comes to mind where the session key maybe wouldn't be sent on the API?

**Comment by ghachey** [comment]
Hi there. Thanks for helping. I have the full package for the remaining season. I did purchase it directly from nhl.tv and then had to create a seperate nhl.com account for the login to work. I think it may be related to this somehow.

I ran the command like this:

```
$ docker run -v /Users/myuser/opt/dl-nhltv:/Users/myuser/opt/dl-nhltv/media -it pontusw/nhltv:latest nhltv --team PIT -u myuser@outlook.com -p mypassword -d media
```

I upgraded to your 2.1.2 and I see the below. Though I am not entirely sure of the arguments looking at your docker example in the README.

```
$ docker run -v /Users/myuser/opt/dl-nhltv:/Users/myuser/opt/dl-nhltv/media -it pontusw/nhltv:latest nhltv --team PIT -u myuser@outlook.com -p mypassword -d media
Jan 23 12:26:23 - Logging in to NHL.com..
Jan 23 12:26:24 - Looking up games..
Traceback (most recent call last):
  File "/usr/local/bin/nhltv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 39, in main
    run_loop()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 44, in run_loop
    loop()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 48, in loop
    get_and_download_games()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 71, in get_and_download_games
    download(i)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 79, in download
    dl: Download = download_game(stream)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/download.py", line 40, in download_game
    download = _get_download_from_stream(stream)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/download.py", line 104, in _get_download_from_stream
    media_auth: str = _extract_media_auth(stream_json)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/download.py", line 187, in _extract_media_auth
    session_json["session_info"]["sessionAttributes"][0][
KeyError: 'session_info'
```

**Comment by ghachey** [comment]
Hi. I have purchased another subscription this time directly from nhl.com instead of directly nhl.tv. And it seems to work differently. This is a really confusing service they offer!

```
$ nhltv --team PIT -u myuser@outlook.com -p mypassword
Jan 23 08:34:26 - Logging in to NHL.com..
Jan 23 08:34:27 - Looking up games..
Jan 23 08:34:33 - Sign-on restriction: Too many usage attempts
```

**Comment by pppontusw** [comment]
> Hi. I have purchased another subscription this time directly from nhl.com instead of directly nhl.tv. And it seems to work differently. This is a really confusing service they offer!
> 
> ```
> $ nhltv --team PIT -u myuser@outlook.com -p mypassword
> Jan 23 08:34:26 - Logging in to NHL.com..
> Jan 23 08:34:27 - Looking up games..
> Jan 23 08:34:33 - Sign-on restriction: Too many usage attempts
> ```

That error is fairly common, if you try to run it a few times or something like that - NHLTV this year have added some very strict restrictions on how often you can connect to the service. However, the program will keep trying every five minutes and eventually it should continue from there - usually it takes 30-60 minutes before the service is "unlocked" again.

Let's see if that new subscription would work once the "sign-on restriction" go away, if not - let me know and I will prepare some more steps so we can debug this thing and see if we can get to the bottom of why it won't work

**Comment by pppontusw** [comment]
Created another release, 2.1.3 - if you're still having issues after the sign-on restriction goes away you could try that version (check that it actually is `2.1.3` before you run, I fixed up some debug code so that it won't contain any secret information) and run it with the --debug argument. It will output some json files into a folder called `dumps` - if you could then share the content of those with me for example with https://pastebin.com/  then I could take a deeper look at what your API response contains so I can see if there's something I can do to make it work

**Comment by ghachey** [comment]
Hi, thanks for the very quick help. It seems to be working now. I can download my games and watch them offline at the cabin thanks to your tool! I think this can be closed, though a more user friendly handling of the error would be nice certainly not necessary (for me anyway). I will leave it up to you if you want to close this. I will install your latest and if anything report back as you suggest.

**Comment by pppontusw** [comment]
Great to hear that it’s working now! 

Yeah, I would certainly like to handle the error more gracefully but it’s hard to say what the actual situation was without being able to reproduce it myself. Any chance you could link me to where you had bought your original subscription (the one that seemed to not work?) so I can maybe check that out and see if I can spot any differences?

**Comment by ghachey** [comment]
I believe it was https://nhllive.com/en/ which is somehow connected to nhl.com but it seems different services. I'm not sure it's worth the trouble in my opinion.

**Comment by pppontusw** [comment]
Okay, thanks for the info - looks like it’s Rogers equivalent of NHLTV but it’s good for me to know then that it doesn’t work with that, in case I see similar issues again!
